### PR TITLE
Addition of local config for database connection

### PR DESCRIPTION
**Pull request by HarveyRDonnelly**
@pandaponn please note this PR as the file upload config should be included in local.properties as well.

### CODE REVIEW

**Comment by pandaponn** [comment]
> @pandaponn please note this PR as the file upload config should be included in local.properties as well.

Yup noted!

**Comment by HarveyRDonnelly** [comment]
Added option to override local config via environment variables following feedback from @pandaponn. This may be used in a  production environment for greater security

**Review by pandaponn — COMMENTED** [review]
Thanks @HarveyRDonnelly for addressing the security concerns regarding my offline feedback, I can now see why there is no security issue. 

Would the local.properties file eventually be changed by the individual developers to suit their own local environment? If that is the case, should this be git ignored since it would result in constant commits for this file? Or are developers supposed to manually leave this out of their commits? Or should this be left as default and untouched by developers? If this is the case, some comments would be helpful towards the developers.

**Comment by HarveyRDonnelly** [comment]
> Thanks @HarveyRDonnelly for addressing the security concerns regarding my offline feedback, I can now see why it is not a security issue.
> 
> Would the local.properties file eventually be changed by the individual developers to suit their own local environment? If that is the case, should this be git ignored since it would result in constant commits for this file? Or are developers supposed to manually leave this out of their commits? Or should this be left as default and untouched by developers? If this is the case, some comments would be helpful towards the developers.

Thank you for the feedback @pandaponn ! I understand your concern regarding the local.properties file. The file should certainly be included in the repo as it is required for the software to run and it is necessary for developers to know what variables must be defined within the config. We could merge this PR and then later add the file to .gitignore so that it is in the repo but changes aren't tracked. There is a small risk, however, of losing the file if `git rm --cached` is ever run and further config file changes could not be easily made. Alternatively, developers could simply override the config file using environment variables (can be done with 'Edit Run Configuration' in IntelliJ) without editing the config file, or they could simply not stage the file when changes are made. I favour the second option as we may wish to make changes or add other config to the file which needs to be tracked. For all of these options, no changes should be made to this PR notably.

**Comment by pandaponn** [comment]
> > Thanks @HarveyRDonnelly for addressing the security concerns regarding my offline feedback, I can now see why it is not a security issue.
> > Would the local.properties file eventually be changed by the individual developers to suit their own local environment? If that is the case, should this be git ignored since it would result in constant commits for this file? Or are developers supposed to manually leave this out of their commits? Or should this be left as default and untouched by developers? If this is the case, some comments would be helpful towards the developers.
> 
> Thank you for the feedback @pandaponn ! I understand your concern regarding the local.properties file. The file should certainly be included in the repo as it is required for the software to run and it is necessary for developers to know what variables must be defined within the config. We could merge this PR and then later add the file to .gitignore so that it is in the repo but changes aren't tracked. There is a small risk, however, of losing the file if `git rm --cached` is ever run and further config file changes could not be easily made. Alternatively, developers could simply override the config file using environment variables (can be done with 'Edit Run Configuration' in IntelliJ) without editing the config file, or they could simply not stage the file when changes are made. I favour the second option as we may wish to make changes or add other config to the file which needs to be tracked. For all of these options, no changes should be made to this PR notably.

Yes I agree with the second option as well, sounds good!

**Review by pandaponn — APPROVED** [review]
Overall, the code looks clean with appropriate exception handling and helpful comments to clearly state the functionalities.

Note from our discussion: "Developers could simply override the config file using environment variables (can be done with 'Edit Run Configuration' in IntelliJ) without editing the config file, or they could simply not stage the file when changes are made"

**Pull request merged**
