### PR TITLE
Updated entities for consistency. Added MessageTree construction to updateState use case.

### PR DESCRIPTION
**Pull request by HarveyRDonnelly**
This pull request contains a number of changes related to the integration of code contributions:
(i) Creating a new CourseInfo interface which is used to track information for all courses without having to track the solution and test documents associated with them;
(ii) Replaced placeholders in the update state tracker use case such that Courses and MessageTree objects are correctly constructed;
(iii) Changed list representations of child entities (e.g. solution docs in a test doc) from lists to dictionaries;
(iv) Updated and added methods in entities as required.

### CODE REVIEW

**Comment by HarveyRDonnelly** [comment]
PostgresAccessManager needs to implement all gateways for project to compile.

**Review by N1cholasMcKee — APPROVED** [review]
These are some really good changes. Saving the solution documents as a "child" of the test document should vastly simplify the entities and use cases when accessing those documents. It looks like you also fixed and extended some of the more haphazardly added entities, which should make coding the use cases easier. The new CourseInfo interface should also simplify the management of courses independent of any associated documents.

**Review by HumrajB — COMMENTED** [review]
This pull request is great! I like the changes made to Tree class and the SubmitDBMessageInteractor. It is also great idea to be using Maps instead of random data structures that are were not consistent throughout the code. I have removed some  comments that were not needed since changes were made. Overall the code looks great and will make great progress once it is merged.

**Review by N1cholasMcKee — APPROVED** [review]
Good Job removing the unnecessary comment, reducing excess bloat in code is important for improving readability and simplicity.

**Pull request merged**
